### ISSUE TITLE
Building on Linux hits an error related to XAudio

### ISSUE THREAD

**Issue by MetalMaxMX** [MrcSnm/HipremeEngine#47]
Hi. I wanted to know if DMD is supported or not? Since it seems that when I'm building through a 'dub build' command I hit: 

modules/audio/source/hip/hipaudio/audioclip.d(57,25): Error: undefined identifier `XAUDIO2_BUFFER`
Error /usr/bin/dmd failed with exit code 1.

And I am not sure why that is happening since Linux does not uses xaudio at all to my knowledge, I built from master too. Perhaps I have to use LDC instead of DMD for a successful compilation? Does the projects states that so? (Or you're not supposed to use dub?)

**Comment by MrcSnm** [comment]
Oh right, so basically, the linux support I'm just reviewing by today. I have basically fixed that XAUDIO2_BUFFER thing, have fixed almost all problems releated to Shared Library loading on linux, and right now I'm fixing input related things to Linux, after that, you'll be pretty much good to go.

Both the DMD and LDC are supported. I'll merge on master in 1 or 2 hours everything I have done today and linux will be usable for you.
