### ISSUE TITLE
ninepatchtest.d incompatible types 

### ISSUE THREAD

**Issue by MetalMaxMX** [MrcSnm/HipremeEngine#49]
Hey! Thanks for taking notice so soon of my reported issue. I noticed that an hour ago or so a new PR was released and most of it was compiling! There is still this error that I'm running into though 

source/hip/view/ninepatchtest.d(32,29): Error: incompatible types for `(getTouchPosition(0u)) - (this.startPatch)`: `float[2]` and `Vector!(2u, float)`
Error /usr/bin/dmd failed with exit code 1.

I do appreciate that most modules and the audio ones were fixed!

**Comment by MrcSnm** [comment]
Humm tis was just fixed, maybe I didn't push it to master, doing it right now
