### ISSUE TITLE
Linking error related to /TIME on Linux

### ISSUE THREAD

**Issue by MetalMaxMX** [MrcSnm/HipremeEngine#58]
Hey there, been awhile. I was updating the repository and I encountered a bug where attempting to run a dub or dub build command nets me a: /usr/bin/ld: cannot find /TIME: No such file or directory
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
Error /usr/bin/dmd failed with exit code 1.

Not sure what is happening here though

**Comment by MrcSnm** [comment]
Seems like my VClinker debug cli option went into the upstream, just a quick fix
