### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by p0nce** [MrcSnm/HipremeEngine#61]
- I took a long time to find the link to: https://github.com/MrcSnm/HipremeEngine/wiki/Getting-Started#getting-started
    - first I tried to look into "projects"
    - then I tried "start_here" in projects. But, not sure what it is in the end, doesn't build with strange DUB error
![image](https://user-images.githubusercontent.com/1067485/211152936-e7106383-d3c9-4eea-a5b4-657676291ed0.png)

    - then I tried to open HipremeEngine.sln, but does not open correctly in VS
    - then I found the big link in README.md, in editor did not really noticed that link before

- follow the tutorial in Getting-Started

- Got a build error:
![image](https://user-images.githubusercontent.com/1067485/211152635-a63b30ce-151a-403d-91dd-a46fa7d4a6b5.png)

**Comment by MrcSnm** [comment]
Humm okay, seems like it is taking the absolute path from my PC, gonna fix that

**Comment by p0nce** [comment]
```
LDC - the LLVM D compiler (1.28.0):
  based on DMD v2.098.0 and LLVM 12.0.1
  built with LDC - the LLVM D compiler (1.28.0)
  Default target: x86_64-pc-windows-msvc
  Host CPU: znver1
  http://dlang.org - http://wiki.dlang.org/LDC
```

**Comment by MrcSnm** [comment]
Okay, I'll add to the toolchain requirements that the dmd-fe required 2.99 as the __traits(parameters) is fairly new. This was introduced recently in my codebase in an attempt to make CTFE a little faster, time to check the return non-void

**Comment by MrcSnm** [comment]
What would make your experience better  for find the Getting Started link?

**Comment by MrcSnm** [comment]
Okay @p0nce Seems like the return non-void from void function happens because it didn't get the correct function [6e088a4](https://github.com/MrcSnm/HipremeEngine/commit/6e088a4aabe3e474f97190e96ab69444f6375165)

I think that may be able to solve, I'm dealing with the start_here  project too.

**Comment by p0nce** [comment]
@MrcSnm I think:
- https://github.com/MrcSnm/HipremeEngine/wiki could link to the getting started in the body
- I think projects/start_here/README.md should could include the link too

**Comment by MrcSnm** [comment]
I have added the Getting Started to the start_here project, and to the wiki
