### ISSUE TITLE
2nd run of the generated project doesn't run

### ISSUE THREAD

**Issue by p0nce** [MrcSnm/HipremeEngine#62]
After a project is generated:

First run of `dub -c run --compiler dmd` run the game.
Repeating `dub -c run --compiler dmd` doesn't run the game.
I didn't expect that.

Here the 2nd run result:
![image](https://user-images.githubusercontent.com/1067485/211153904-f16c80e4-aa50-4fa7-b522-aa6fd60fba06.png)

Using `dub -c run --compiler dmd -f` makes it run again.

**Comment by MrcSnm** [comment]
Yes, I have been having a complicated time dealing with that too. Do you know if there is a way to force dub to always execute a command even if it is up to date?

**Comment by MrcSnm** [comment]
Btw, HipremeEngine has a test project with more functions and documentation if you run `dub` on the engine itself. Do you think I should mirror this test scene on start_here or a blank project is better?

**Comment by p0nce** [comment]
>  I have been having a complicated time dealing with that too. Do you know if there is a way to force dub to always execute a command even if it is up to date?

I don't know, it is possible to provide -f to the documentation reader for now I think. Or it could be an info message at tart of program log.

>  Do you think I should mirror this test scene on start_here or a blank project is better?

I made a separate issue, I understood that it was a blank project now but this made me wonder if the example was working. non-blank is an opportunity to show off your features.

**Comment by MrcSnm** [comment]
Okay, so, for the time being, I'll make it mirror the test scene.
The project generator will be what the start_here has today

**Comment by MrcSnm** [comment]
#66  fixed that. Using postGenerateCommands instead of postBuildCommands was the solution
