### ISSUE TITLE
Not sure if example working?

### ISSUE THREAD

**Issue by p0nce** [MrcSnm/HipremeEngine#63]
I was kindof expecting something on screen, but the generated project is a black screen. 
**What I was expecting:** anything else, even a plain non-black color rectangle, so that I know the engine is working as intended.
**What I see:** black window

Setup: Windows 11, dmd `DMD32 D Compiler v2.101.0-beta.1-dirty`, DUB 1.27.0

![image](https://user-images.githubusercontent.com/1067485/211154169-eee231d0-f0fa-4410-8aae-73d8332cf265.png)

**Comment by MrcSnm** [comment]
The new project generator shows a text on blank project
