### ISSUE TITLE
Audio modules error

### ISSUE THREAD

**Issue by MetalMaxMX** [MrcSnm/HipremeEngine#67]
Hi! Immediately after updating your repo and getting everything right, I got another issue using dmd, here: 

modules/audio/source/hip/hipaudio/audioclip.d(43,5): Error: static assert:  "HipAudioBuffer must have same size as a ptr, _getBufferAPI depends on that"
Error /usr/bin/dmd failed with exit code 1.

Running a standard dub, Debian 11 once more.

**Comment by MrcSnm** [comment]
Oh this is one really annoying bug! I've relied on a hack for making that work so I'm going to think on another way

**Comment by MrcSnm** [comment]
@MetalMaxMX Fixed :)
