### ISSUE TITLE
start_here: DUB postGenerateCommand assumes Windows

### ISSUE THREAD

**Issue by 0xEAB** [MrcSnm/HipremeEngine#80]
The `postGenerateCommand` in the DUB recipe of the *start_here* project  assumes that the user is running Windows (or any OS with backslash `\` as its directory separator).

https://github.com/MrcSnm/HipremeEngine/blob/40eeb64659107f7bedf082e3ff1b1c2d7a9193e9/projects/start_here/dub.json#L51

On other platforms building fails with `/bin/sh: 1: cd: can't cd to ....` or similar.

**Comment by 0xEAB** [comment]
A clean solution could be to make the script runner available as a dub package, so that the user would run `dub run hipremeengine:script`. Please note that I don’t have enough understanding of the codebase to know whether this suggestion is actually reasonable or feasible.

**Comment by MrcSnm** [comment]
I'll starter by using `postGenerateCommands-os` then
