### ISSUE TITLE
windowing: Linking fails on Debian

### ISSUE THREAD

**Issue by 0xEAB** [MrcSnm/HipremeEngine#81]
```
…/HipremeEngine/projects/start_here$ dub -c run
ld: error: cannot open /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/X11: Is a directory
```

Seems like the cause is the following line:
https://github.com/MrcSnm/HipremeEngine/blob/494b67bf50f24273ccf3ab8d2bb8ab07a82e2df2/modules/windowing/source/hip/windowing/platforms/x11lib/x11.d#L10

`X11` should probably be `x11` here.
Furthermore, this `pragma` seems kinda redundant, as the lib is scheduled for linking in the DUB recipe already:

https://github.com/MrcSnm/HipremeEngine/blob/494b67bf50f24273ccf3ab8d2bb8ab07a82e2df2/modules/windowing/dub.json#L9

Funny enough, linking seems to work fine with a capital `X` here.

Oh and: This is on Debian 11 “Bullseye” on an x86-64 machine.

**Comment by MrcSnm** [comment]
I'm pretty sure that is related to a later adding of me this dub.json "X11" as I got some problem with `pragma(lib)` started being ignored in dub staticLibrary targetType.

**Comment by MrcSnm** [comment]
I'm gonna maintain that only on dub then

**Comment by 0xEAB** [comment]
addendum: related to *lld*, cannot reproduce with *gold*
