### ISSUE TITLE
`setFont()` interferes with `drawRectangle()`

### ISSUE THREAD

**Issue by 0xEAB** [MrcSnm/HipremeEngine#84]
`setFont()` interferes with `drawRectangle()` and makes it actually `fillRectangle()`.

### double setFont()

```d
override void render()
{
    setFont(smallFont);
    drawRectangle(40, 40, 200, 200, HipColor(1, 0, 0.5, 1));
    setFont(null);

    renderGeometries();
    renderTexts();
    renderSprites();
}
```
![image](https://user-images.githubusercontent.com/15967408/227674895-5630b9c5-306e-4408-aec6-d2209075cec3.png)

### no or single setFont()

```d
override void render()
{
    drawRectangle(40, 40, 200, 200, HipColor(1, 0, 0.5, 1));
    setFont(null);

    renderGeometries();
    renderTexts();
    renderSprites();
}
```

It makes no difference whichever one is omitted. Bug only occurs when both are there.

![image](https://user-images.githubusercontent.com/15967408/227675107-7cdc1a71-b5dd-4dd5-ba1b-33f7921d288a.png)

**Comment by MrcSnm** [comment]
I think that will be fixed as soon as I merge the current metal branch. There is a bunch of things changing from behind the scenes (performance upgrades also). The changes on user code will be that you won't need to call renderGeometries(), renderSprites() and renderTexts() anymore too, they will all be managed automaticaly
